[workspace]
resolver = "3"
members = [
    "avin",
    "avin_analyse",
    "avin_connect",
    "avin_core",
    "avin_strategy",
    "avin_tester",
    "avin_trader",
    "avin_utils"
]

[workspace.package]
description = "Open source cross-platform trading system"
version = "0.2.6"
edition = "2024"
license = "MIT"
readme = "README.md"
authors = ["Alex Avin <mr.alexavin@gmail.com>"]
repository = "https://github.com/arsvincere/avin"
homepage = "https://avin.info"
keywords = ["trading", "algo-trading", "algorithmic_trading", "moex", "tinkoff", "t-bank"]
categories = ["Algorithmic Trading"]

[workspace.dependencies]
bitcode = "0.6.5"
cached = "0.55.1"
chrono = "0.4.41"
flume = "0.11.1"
log = "0.4.27"
polars = { version = "0.49.1", features = [
    "cum_agg", # for Expr.cum_sum()
    "describe",
    "is_in",
    "lazy",
    "parquet",
    "temporal",
    # "is_between",
    # "json",
    # "polars-ops", # for Series.cum_sum()
    # "strings",
] }
serde = "1.0.219"
strum = { version = "0.27.1", features = ["derive", "strum_macros"]}
time-unit = "0.1"
tokio = { version = "1", features = ["full"] }
toml = "0.8.23"
tonic = { version = "0.11", features = ["tls", "tls-roots", "gzip"] }
uuid = {version = "1.16.0", features = [ "v4" ]}
prost-types = "0.12"
prost = "0.12"

# self crates
avin = { version = "0.2.6", path = "avin" }
avin_analyse = { version = "0.2.6", path = "avin_analyse" }
avin_connect = { version = "0.2.6", path = "avin_connect" }
avin_core = { version = "0.2.6", path = "avin_core" }
avin_strategy = { version = "0.2.6", path = "avin_strategy" }
avin_tester = { version = "0.2.6", path = "avin_tester" }
avin_trader = { version = "0.2.6", path = "avin_trader" }
avin_utils = { version = "0.2.6", path = "avin_utils" }
